apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chaos-test-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - service: checkout
            valuesFile: checkout-chaos.yaml
          - service: orders
            valuesFile: orders-chaos.yaml
          - service: payment
            valuesFile: payment-chaos.yaml
  template:
    metadata:
      name: chaos-{{service}}
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/chaos-injection.git
        targetRevision: main
        path: charts/istio-chaos
        helm:
          valueFiles:
            - ../../environments/production/{{valuesFile}}
      destination:
        server: https://kubernetes.default.svc
        namespace: production
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
