apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chaos-test-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - service: httpbin
            valuesFile: http-bin.yaml
  template:
    metadata:
      name: chaos-{{service}}
    spec:
      project: default
      source:
        repoURL: https://github.com/ahramadan/chaos-injection.git
        targetRevision: main
        path: charts/istio-chaos
        helm:
          valueFiles:
            - "{{valuesFile}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
