global:
  serviceName: "httpbin"
  namespace: "default"
  serviceHost: "httpbin.default.svc.cluster.local"
  subset: "v1"
  headerValue: "true"

profiles:
  abort:
    enabled: false
    statusCode: 503
    percentage: 10

  delay:
    enabled: true
    delay: "10s"           # delay the response by 10 seconds
    percentage: 100
    
  unreachable:
    enabled: false

