global:
  serviceName: "httpbin"
  namespace: "default"
  serviceHost: "httpbin.default.svc.cluster.local"
  headerValue: "true"

profile:
  enabled: true
  name: unreachable
  matchHeader: x-chaos-test

  delay:
    enabled: true
    fixedDelay: "10s"
    percentage: 40

  abort:
    enabled: true
    statusCode: 504
    percentage: 20
