global:
  serviceName: "httpbin"
  namespace: "default"
  serviceHost: "httpbin.default.svc.cluster.local"
  subset: "v1"
  headerValue: "true"

profile:
  enabled: true
  name: unreachable
  matchHeader: x-chaos-httpbin

  delay:
    enabled: true
    fixedDelay: "5s"
    percentage: 40

  abort:
    enabled: true
    statusCode: 503
    percentage: 10
