global:
  serviceName: "httpbin"
  namespace: "default"
  serviceHost: "httpbin.default.svc.cluster.local"
  subset: "v1"
  headerValue: "true"

profiles:
  abort:
    enabled: true
    statusCode: 503
    percentage: 10

  delay:
    enabled: true
    delay: "10s"
    percentage: 100
    
  unreachable:
    enabled: false
    delay: "10s"
    statusCode: 504
    percentage: 100

