global:
  serviceName: "httpbin"
  namespace: "default"
  serviceHost: "httpbin.default.svc.cluster.local"
  subset: "v1"
  headerValue: "true"

profiles:
  unreachable:
    enabled: true
    delay: "5s"
    statusCode: 503
    percentage: 40
