global:
  serviceName: "httpbin"
  namespace: "default"
  serviceHost: "httpbin.default.svc.cluster.local"
  subset: "v1"
  headerValue: "true"

profile:
  enabled: false
  name: zombie-service
  matchHeader: x-chaos-test

  delay:
    enabled: false
    fixedDelay: "10s"
    percentage: 40

  abort:
    enabled: true
    statusCode: 504
    percentage: 100
