global:
  serviceName: "httpbin"
  namespace: "default"
  serviceHost: "httpbin.default.svc.cluster.local"
  subset: "v1"
  headerValue: "true"

profiles:
  abort:
    enabled: true
    statusCode: 503
    percentage: 50

  delay:
    enabled: true
    delay: "5s"
    percentage: 50
    
  unreachable:
    enabled: true
    delay: "5s"
    statusCode: 503
    percentage: 50

