global:
  serviceName: "httpbin"
  namespace: "default"
  serviceHost: "httpbin.default.svc.cluster.local"
  subset: "v1"
  headerValue: "true"

profile:
  enabled: true
  name: "unreachable"
  matchHeader: "x-chaos-profile"
  percentage: 50
  delay: "5s"
  abortStatus: 503
