{{- if .Values.profiles.delay.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.global.serviceName }}-delay
  namespace: {{ .Values.global.namespace }}
spec:
  hosts:
    - {{ .Values.global.serviceHost }}
  http:
    - match:
        - headers:
            x-chaos-test:
              exact: {{ .Values.global.headerValue | quote }}
      timeout: {{ .Values.profiles.delay.timeout | default "2s" | quote }}
      retries:
        attempts: 2
        perTryTimeout: 2s

      route:
        - destination:
            host: {{ .Values.global.serviceHost }}
            subset: {{ .Values.global.subset }}
{{- end }}
