{{- if false }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.global.serviceName }}-unreachable
  namespace: {{ .Values.global.namespace }}
spec:
  hosts:
    - {{ .Values.global.serviceHost }}
  http:
    - match:
        - headers:
            x-chaos-test:
              exact: {{ .Values.global.headerValue | quote }}
      fault:
        delay:
          fixedDelay: {{ .Values.profiles.unreachable.delay | quote }}
          percentage:
            value: {{ .Values.profiles.unreachable.percentage }}
        abort:
          httpStatus: {{ .Values.profiles.unreachable.statusCode }}
          percentage:
            value: {{ .Values.profiles.unreachable.percentage }}
      route:
        - destination:
            host: {{ .Values.global.serviceHost }}
            subset: {{ .Values.global.subset }}
{{- end }}
