{{- $profile := .Values.profile }}
{{- if $profile.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $.Values.global.serviceName }}-{{ $profile.name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  hosts:
    - {{ $.Values.global.serviceHost }}
  http:
    - name: {{ $profile.name }}
      match:
        - headers:
            {{ $profile.matchHeader }}:
              exact: {{ $.Values.global.headerValue | quote }}
      fault:
{{- if and $profile.delay }}
        delay:
          fixedDelay: {{ $profile.delay | quote }}
{{- end }}
{{- if and $profile.abortStatus }}
        abort:
          httpStatus: {{ $profile.abortStatus }}
{{- end }}
{{- if or $profile.delay $profile.abortStatus }}
        percentage:
          value: {{ $profile.percentage }}
{{- end }}
      route:
        - destination:
            host: {{ $.Values.global.serviceHost }}
            subset: {{ $.Values.global.subset }}
{{- end }}
