{{- $profile := .Values.profile }}
{{- if $profile.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $.Values.global.serviceName }}-{{ $profile.name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  hosts:
    - {{ $.Values.global.serviceHost }}
  http:
    - match:
        - headers:
            {{ $profile.matchHeader | default "x-chaos-test" }}:
              exact: {{ $.Values.global.headerValue | quote }}
      fault:
{{- if $profile.delay.enabled }}
        delay:
          fixedDelay: {{ $profile.delay.fixedDelay | quote }}
          percentage:
            value: {{ $profile.delay.percentage }}
{{- end }}
{{- if $profile.abort.enabled }}
        abort:
          httpStatus: {{ $profile.abort.statusCode }}
          percentage:value: {{ $profile.abort.percentage }}
{{- end }}
      route:
        - destination:
            host: {{ $.Values.global.serviceHost }}
            subset: {{ $.Values.global.subset }}
{{- end }}
